language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
  - PLONE_VERSION=5.0
matrix:
  allow_failures:
    - env: PLONE_VERSION=4.2
    - env: PLONE_VERSION=5.0
before_install:
  - sudo apt-get install -y libjpeg-dev libgif-dev libpng-dev libz-dev ghostscript
  - mkdir -p buildout-cache/downloads
  - mkdir -p buildout-cache/eggs
install:
  - sed -ie "s#test-plone-4.3.x.cfg#test-plone-$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script:
  - test -n $QA && bin/code-analysis
  - bin/test
after_success:
  - test -n $QA && bin/createcoverage run bin/test && pip install -q coveralls && coveralls || true
after_failure:
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
